quarkus:
  devservices:
    enabled: false
  log:
    level: INFO
    category:
      "com.rhe":
        level: DEBUG
  kafka-streams:
    topics: etrm.transaction,etrm.public.trade_header,etrm.public.trade_header
    bootstrap-servers: localhost:9094
    auto:
      offset:
        reset: earliest
    state:
      dir: /tmp/kstreams